metrics:
  metric_1:
    metric_name: omega
    file: /path/to/file
    global_loc: select between yes, no
    multi: select between yes, no
    impact:
    - select between essential_splice, missense, nonsense, nonsynonymous_splice, splice_region_variant,
      truncating
    - ''
    significance_threshold: recommended 0.05 (if no filtering by significance, choose
      1)
    elements_total_by: select between none, included, sum, mean, median
    samples_total_by: select between none, included, sum, mean, median
  metric_2:
    metric_name: mutreadsdensity
    file: /path/to/all_mutdensities.tsv
    region:
    - select between all, protein_affecting, non_protein_affecting, synonymous
    - ''
    muttype:
    - select between all, snv, indel, snv_indel
    - ''
    adjust: select between yes, no
    elements_total_by: select between none, included, sum, mean, median
    samples_total_by: select between none, included, sum, mean, median
general:
  output_dir: /path/to/dir
  handle_na: "select between ignore, mean, all_samples \n    (move this field to the\
    \ specific metric section if you want a metric-specific NA handling)"
  elements: add list of elements or regex. Move this field to the specific metric
    section if the subset by elements is not general
  samples: add list of samples or regex. Move this field to the specific metric section
    if the subset by samples is not general
  model: select between linear, linear-mixed-effects
  multi: select between yes, no
  predictors_file: path/to/file
  sample_column: add sample column name
  predictors: column names in predictors file (if empty, all colnames in predictor
    file will be used)
  predictors_intercept_0: leave empty if NA
  predictor_random_effect: leave empty if NA
  predictors_multi_force: leave empty if NA
  correct_pvals: select between yes or no
  significance_threshold: leave empty if no multiple testing correction
plot:
  predictors_names: (optional) add names for your predictors (same order as above)
  predictors_colors: (optional) add color codes for your predictors (same order as
    above)
