metrics:
  metric_1:
    metric_name: mutreadsdensity
    file: /path/to/all_mutdensities.tsv
    region:
    - select between all, protein_affecting, non_protein_affecting, synonymous
    - ''
    muttype:
    - select between all, snv, indel, snv_indel
    - ''
    adjust: select between yes, no
    elements_total_by: select between none, included, sum, mean, median
    samples_total_by: select between none, included, sum, mean, median
  metric_2:
    metric_name: mutreadsdensity
    file: /path/to/all_mutdensities.tsv
    region:
    - select between all, protein_affecting, non_protein_affecting, synonymous
    - ''
    muttype:
    - select between all, snv, indel, snv_indel
    - ''
    adjust: select between yes, no
    elements_total_by: select between none, included, sum, mean, median
    samples_total_by: select between none, included, sum, mean, median
general:
  output_dir: /path/to/dir
  handle_na: select between ignore, mean, all_samples
